### ISSUE TITLE
Can't add color SVG glyph on Windows

### ISSUE THREAD

**Issue by s40king** [googlei18n/noto-emoji#23]
I use Windows7 and python 2.7 , when I try to add SVG glyphs to font , it says
 
 
D:\>D:\noto-emoji-master\add_svg_glyphs.py
Traceback (most recent call last):
  File "D:\noto-emoji-master\add_svg_glyphs.py", line 37, in <module>
    import add_emoji_gsub
  File "D:\noto-emoji-master\add_emoji_gsub.py", line 28, in <module>
    from nototools import font_data
  File "C:\Python27\lib\site-packages\nototools-0.0.1-py2.7.egg\nototools\font_d
ata.py", line 21, in <module>
    from nototools import opentype_data
  File "C:\Python27\lib\site-packages\nototools-0.0.1-py2.7.egg\nototools\openty
pe_data.py", line 327, in <module>
    _set_ompl()
  File "C:\Python27\lib\site-packages\nototools-0.0.1-py2.7.egg\nototools\openty
pe_data.py", line 33, in _set_ompl
    unicode_data.load_data()
  File "C:\Python27\lib\site-packages\nototools-0.0.1-py2.7.egg\nototools\unicod
e_data.py", line 64, in load_data
    _load_unicode_data_txt()
  File "C:\Python27\lib\site-packages\nototools-0.0.1-py2.7.egg\nototools\unicod
e_data.py", line 446, in _load_unicode_data_txt
    decomposition = [unichr(int(char, 16)) for char in decomposition]
ValueError: unichr() arg not in range(0x10000) (narrow Python build)

**Comment by dougfelt** [comment]
Hmmm.  You need a build of python that uses UCS4 Unicode characters, I think.  The ones we use do by default.  I'm not sure we can find and fix all places in the code where we make this assumption without having a narrow build of python to try all the tools on.

**Comment by s40king** [comment]
@behdad  @davelab6

**Comment by behdad** [comment]
What Doug said.  It's your Python version.  You need the "wide build".
