### ISSUE TITLE
Currently does not build

### ISSUE THREAD

**Issue by daidoji** [googlei18n/noto-emoji#44]
Tried following the instructions for building the color emojis and the project fails to build.  Python step installed correctly then.

`daidoji@darkstar:~/noto/nototools$ make         
Makefile:37: target 'packages' given more than once in the same rule
find:`./fonts/individual': No such file or directory
make: **\* No rule to make target 'fonts/individual/hinted/*.ttf', needed by 'hintedtarball'.  Stop.
`

**Comment by dougfelt** [comment]
To build the color emoji, you need to be in the noto-emoji directory and run make from there.

The Makefile in nototools is out of date.

**Comment by daidoji** [comment]
Ahhh, I was just following the instructions in the README.  I will try
that.  Thank you.

Charles Lanahan
charles@revup.com

**Comment by daidoji** [comment]
I'm afraid that didn't seem to work either.

daidoji@darkstar:~/noto/noto-emoji$ PYTHONPATH=../nototools make
which: no zopflipng in
(/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/lib64/qt/bin:/usr/lib64/java/bin:/usr/sbin:/sbin)
which: no optipng in
(/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/lib64/qt/bin:/usr/lib64/java/bin:/usr/sbin:/sbin)
Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/home/daidoji/noto/noto-emoji/add_emoji_gsub.py", line 28, in
<module>
    from nototools import font_data
ImportError: No module named nototools
Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/home/daidoji/noto/noto-emoji/add_emoji_gsub.py", line 28, in
<module>
    from nototools import font_data
ImportError: No module named nototools
Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/home/daidoji/noto/noto-emoji/add_emoji_gsub.py", line 28, in
<module>
    from nototools import font_data
ImportError: No module named nototools
Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/home/daidoji/noto/noto-emoji/add_emoji_gsub.py", line 28, in
<module>
    from nototools import font_data
ImportError: No module named nototools
Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/home/daidoji/noto/noto-emoji/add_emoji_gsub.py", line 28, in
<module>
    from nototools import font_data
ImportError: No module named nototools
Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/home/daidoji/noto/noto-emoji/add_emoji_gsub.py", line 28, in
<module>
    from nototools import font_data
ImportError: No module named nototools
Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/home/daidoji/noto/noto-emoji/add_emoji_gsub.py", line 28, in
<module>
    from nototools import font_data
ImportError: No module named nototools
Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/home/daidoji/noto/noto-emoji/add_emoji_gsub.py", line 28, in
<module>
    from nototools import font_data
ImportError: No module named nototools
Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/home/daidoji/noto/noto-emoji/add_emoji_gsub.py", line 28, in
<module>
    from nototools import font_data
ImportError: No module named nototools
Makefile:125: *** "neither zopflipng nor optipng is available".  Stop.

Charles Lanahan
charles@revup.com

**Comment by dougfelt** [comment]
Oops, my bad.  There's a dependency on optipng.  The makefile should probably proceed properly if neither optipng nor zoplifpng is installed and just not compress, unfortunately it just fails to copy the files.  For now you can get optipng from http://optipng.sourceforge.net/

It looks like you're still getting ImportErrors.  I'd have expected setting PYTHONPATH to work, but I haven't tried that for awhile so perhaps it got broken.  You can try 'cd nototools; sudo python setup.py develop' if those still occur.

**Comment by dougfelt** [comment]
Closing due to inactivity.  The docker environment might help with this once some more kinks are worked out.
