### ISSUE TITLE
ImportError: cannot import name unichr

### ISSUE THREAD

**Issue by Tognee** [googlei18n/noto-emoji#65]
When I try to run the makefile I get this:

Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/mnt/d/Programmi/noto-emoji-master/add_emoji_gsub.py", line 28, in <module>
    from nototools import font_data
  File "/mnt/d/Programmi/nototools-master/nototools/font_data.py", line 21, in <module>
    from nototools import opentype_data
  File "/mnt/d/Programmi/nototools-master/nototools/opentype_data.py", line 22, in <module>
    from nototools import unicode_data
  File "/mnt/d/Programmi/nototools-master/nototools/unicode_data.py", line 36, in <module>
    from fontTools.misc.py23 import unichr
ImportError: cannot import name unichr
Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/mnt/d/Programmi/noto-emoji-master/add_emoji_gsub.py", line 28, in <module>
    from nototools import font_data
  File "/mnt/d/Programmi/nototools-master/nototools/font_data.py", line 21, in <module>
    from nototools import opentype_data
  File "/mnt/d/Programmi/nototools-master/nototools/opentype_data.py", line 22, in <module>
    from nototools import unicode_data
  File "/mnt/d/Programmi/nototools-master/nototools/unicode_data.py", line 36, in <module>
    from fontTools.misc.py23 import unichr
ImportError: cannot import name unichr
Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/mnt/d/Programmi/noto-emoji-master/add_emoji_gsub.py", line 28, in <module>
    from nototools import font_data
  File "/mnt/d/Programmi/nototools-master/nototools/font_data.py", line 21, in <module>
    from nototools import opentype_data
  File "/mnt/d/Programmi/nototools-master/nototools/opentype_data.py", line 22, in <module>
    from nototools import unicode_data
  File "/mnt/d/Programmi/nototools-master/nototools/unicode_data.py", line 36, in <module>
    from fontTools.misc.py23 import unichr
ImportError: cannot import name unichr
Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/mnt/d/Programmi/noto-emoji-master/add_emoji_gsub.py", line 28, in <module>
    from nototools import font_data
  File "/mnt/d/Programmi/nototools-master/nototools/font_data.py", line 21, in <module>
    from nototools import opentype_data
  File "/mnt/d/Programmi/nototools-master/nototools/opentype_data.py", line 22, in <module>
    from nototools import unicode_data
  File "/mnt/d/Programmi/nototools-master/nototools/unicode_data.py", line 36, in <module>
    from fontTools.misc.py23 import unichr
ImportError: cannot import name unichr
Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/mnt/d/Programmi/noto-emoji-master/add_emoji_gsub.py", line 28, in <module>
    from nototools import font_data
  File "/mnt/d/Programmi/nototools-master/nototools/font_data.py", line 21, in <module>
    from nototools import opentype_data
  File "/mnt/d/Programmi/nototools-master/nototools/opentype_data.py", line 22, in <module>
    from nototools import unicode_data
  File "/mnt/d/Programmi/nototools-master/nototools/unicode_data.py", line 36, in <module>
    from fontTools.misc.py23 import unichr
ImportError: cannot import name unichr
Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/mnt/d/Programmi/noto-emoji-master/add_emoji_gsub.py", line 28, in <module>
    from nototools import font_data
  File "/mnt/d/Programmi/nototools-master/nototools/font_data.py", line 21, in <module>
    from nototools import opentype_data
  File "/mnt/d/Programmi/nototools-master/nototools/opentype_data.py", line 22, in <module>
    from nototools import unicode_data
  File "/mnt/d/Programmi/nototools-master/nototools/unicode_data.py", line 36, in <module>
    from fontTools.misc.py23 import unichr
ImportError: cannot import name unichr
Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/mnt/d/Programmi/noto-emoji-master/add_emoji_gsub.py", line 28, in <module>
    from nototools import font_data
  File "/mnt/d/Programmi/nototools-master/nototools/font_data.py", line 21, in <module>
    from nototools import opentype_data
  File "/mnt/d/Programmi/nototools-master/nototools/opentype_data.py", line 22, in <module>
    from nototools import unicode_data
  File "/mnt/d/Programmi/nototools-master/nototools/unicode_data.py", line 36, in <module>
    from fontTools.misc.py23 import unichr
ImportError: cannot import name unichr
Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/mnt/d/Programmi/noto-emoji-master/add_emoji_gsub.py", line 28, in <module>
    from nototools import font_data
  File "/mnt/d/Programmi/nototools-master/nototools/font_data.py", line 21, in <module>
    from nototools import opentype_data
  File "/mnt/d/Programmi/nototools-master/nototools/opentype_data.py", line 22, in <module>
    from nototools import unicode_data
  File "/mnt/d/Programmi/nototools-master/nototools/unicode_data.py", line 36, in <module>
    from fontTools.misc.py23 import unichr
ImportError: cannot import name unichr
Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/mnt/d/Programmi/noto-emoji-master/add_emoji_gsub.py", line 28, in <module>
    from nototools import font_data
  File "/mnt/d/Programmi/nototools-master/nototools/font_data.py", line 21, in <module>
    from nototools import opentype_data
  File "/mnt/d/Programmi/nototools-master/nototools/opentype_data.py", line 22, in <module>
    from nototools import unicode_data
  File "/mnt/d/Programmi/nototools-master/nototools/unicode_data.py", line 36, in <module>
    from fontTools.misc.py23 import unichr
ImportError: cannot import name unichr
using optipng

And than it stops.

**Comment by dougfelt** [comment]
Do you have behdad/fontTools from upstream?

https://github.com/behdad/fonttools/blob/master/Lib/fontTools/misc/py23.py

**Comment by Tognee** [comment]
I installed it with the command described in the nototools readme
`pip install -r requirements.txt`

After installing from source it worked
