### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by nebfield** [googlei18n/noto-emoji#96]
Hi,

I'm trying to build per the instructions provided but I'm getting the following error message:

```
(emoji) benjamfield@beats-working:~/bin/noto-emoji$ make
using optipng
cannot process alias fe82b -> unknown_flag
Traceback (most recent call last):
  File "add_glyphs.py", line 403, in <module>
    main()
  File "add_glyphs.py", line 399, in main
    args.aliases)
  File "add_glyphs.py", line 372, in update_ttx
    update_font_data(font, seq_to_advance, aliases)
  File "add_glyphs.py", line 333, in update_font_data
    add_ligature_sequences(font, seqs, aliases)
  File "add_glyphs.py", line 325, in add_ligature_sequences
    add_ligature(lookup, cmap, seq, name)
  File "add_glyphs.py", line 308, in add_ligature
    ligatures = lookup.SubTable[0].ligatures
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 557, in __getattr__
    raise AttributeError(attr)
AttributeError: ligatures
Makefile:197: recipe for target 'NotoColorEmoji.tmpl.ttx' failed
make: *** [NotoColorEmoji.tmpl.ttx] Error 1
```

I'm running xubuntu 16.04.

Thanks!

**Comment by dougfelt** [comment]
I've been changing this recently, so it's a little flaky.  I've been working around an issue in fontTools-- it wasn't fleshing out the lookups it builds when reading in the .ttx file and so I was patching them.  It looks like the code here isn't catching this if LookupType is defined but the ligatures attribute wasn't set.  I'm not hitting this problem for some reason, perhaps my version of fontTools is slightly different.

Try this and let me know:

```
    # importXML doesn't fully init GSUB structures, so help it out
    st = lookup.SubTable[0]
    if not hasattr(lookup, 'LookupType'):
      assert st.LookupType == 4
      setattr(lookup, 'LookupType', 4)
    if not hasattr(st, 'ligatures'):
      setattr(st, 'ligatures', {})
```

**Comment by benjamfield** [comment]
Hi,

I tried what you suggested and now I'm getting the following:

```
(emoji) benjamfield@beats-working:~/bin/noto-emoji$ make
using optipng
cannot process alias fe82b -> unknown_flag
Traceback (most recent call last):
  File "add_glyphs.py", line 402, in <module>
    main()
  File "add_glyphs.py", line 398, in main
    args.aliases)
  File "add_glyphs.py", line 373, in update_ttx
    font.saveXML(out_file)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 308, in saveXML
    self._tableToXML(tableWriter, tag, progress)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 346, in _tableToXML
    table.toXML(writer, self)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 113, in toXML
    self.table.toXML2(writer, font)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 721, in toXML2
    conv.xmlWrite(xmlWriter, font, value, conv.name, [])
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 332, in xmlWrite
    value.toXML(xmlWriter, font, attrs, name=name)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 702, in toXML
    self.toXML2(xmlWriter, font)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 716, in toXML2
    [("index", i)])
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 332, in xmlWrite
    value.toXML(xmlWriter, font, attrs, name=name)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 702, in toXML
    self.toXML2(xmlWriter, font)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 716, in toXML2
    [("index", i)])
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 413, in xmlWrite
    Table.xmlWrite(self, xmlWriter, font, value, None, attrs)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 332, in xmlWrite
    value.toXML(xmlWriter, font, attrs, name=name)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 775, in toXML
    BaseTable.toXML(self, xmlWriter, font, attrs, name)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 702, in toXML
    self.toXML2(xmlWriter, font)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 721, in toXML2
    conv.xmlWrite(xmlWriter, font, value, conv.name, [])
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 332, in xmlWrite
    value.toXML(xmlWriter, font, attrs, name=name)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 775, in toXML
    BaseTable.toXML(self, xmlWriter, font, attrs, name)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 702, in toXML
    self.toXML2(xmlWriter, font)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otTables.py", line 471, in toXML2
    items = sorted(self.classDefs.items())
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 557, in __getattr__
    raise AttributeError(attr)
AttributeError: classDefs
Makefile:197: recipe for target 'NotoColorEmoji.tmpl.ttx' failed
make: *** [NotoColorEmoji.tmpl.ttx] Error 1
rm NotoColorEmoji.tmpl.ttx
```
Thanks!

**Comment by dougfelt** [comment]
Hmmm.  What version of fontTools are you using?  I have
$ ttx --version
3.7.2.dev0

**Comment by benjamfield** [comment]
I had installed fonttools via pip: 
```
ttx --version
3.2.1
```
I have updated to 3.7.3.dev0 and am getting the same error.

**Comment by dougfelt** [comment]
Sorry, it's difficult to track this down since I'm not able to reproduce this error.

Try updating both noto-emoji and nototools to head.  Then at the top of noto-emoji/add_glyphs.py after the PNG import add the following lines:

```
import logging
logging.basicConfig(level=logging.DEBUG)
```

run make clean and make sure NotoColorEmoji.tmpl.ttx and NotoColorEmoji.tmpl.ttf are not present, then run make.  then at least we can see which table is causing the problem.

**Comment by bitfag** [comment]
I'm experiencing the same issue on ubuntu 16.04. With the logging added as described above I'm getting the following output:


```
...
optipng -quiet -o7 -clobber -force -out "build/compressed_pngs/emoji_u1f1ff_1f1f2.png" "build/quantized_pngs/emoji_u1f1ff_1f1f2.png"
optipng -quiet -o7 -clobber -force -out "build/compressed_pngs/emoji_u1f1ff_1f1fc.png" "build/quantized_pngs/emoji_u1f1ff_1f1fc.png"
optipng -quiet -o7 -clobber -force -out "build/compressed_pngs/emoji_u1f3f4_e0067_e0062_e0065_e006e_e0067_e007f.png" "build/quantized_pngs/emoji_u1f3f4_e0067_e0062_e0065_e006e_e0067_e007f.png"
optipng -quiet -o7 -clobber -force -out "build/compressed_pngs/emoji_u1f3f4_e0067_e0062_e0073_e0063_e0074_e007f.png" "build/quantized_pngs/emoji_u1f3f4_e0067_e0062_e0073_e0063_e0074_e007f.png"
optipng -quiet -o7 -clobber -force -out "build/compressed_pngs/emoji_u1f3f4_e0067_e0062_e0077_e006c_e0073_e007f.png" "build/quantized_pngs/emoji_u1f3f4_e0067_e0062_e0077_e006c_e0073_e007f.png"
cannot process alias fe82b -> unknown_flag
INFO:fontTools.misc.xmlReader:Parsing 'GlyphOrder' table...
INFO:fontTools.misc.xmlReader:Parsing 'head' table...
INFO:fontTools.misc.xmlReader:Parsing 'hhea' table...
INFO:fontTools.misc.xmlReader:Parsing 'maxp' table...
INFO:fontTools.misc.xmlReader:Parsing 'OS/2' table...
INFO:fontTools.misc.xmlReader:Parsing 'hmtx' table...
INFO:fontTools.misc.xmlReader:Parsing 'vhea' table...
INFO:fontTools.misc.xmlReader:Parsing 'vmtx' table...
INFO:fontTools.misc.xmlReader:Parsing 'cmap' table...
INFO:fontTools.misc.xmlReader:Parsing 'name' table...
INFO:fontTools.misc.xmlReader:Parsing 'post' table...
INFO:fontTools.misc.xmlReader:Parsing 'GSUB' table...
Traceback (most recent call last):
  File "add_glyphs.py", line 410, in <module>
    main()
  File "add_glyphs.py", line 406, in main
    args.aliases)
  File "add_glyphs.py", line 379, in update_ttx
    update_font_data(font, seq_to_advance, vadvance, aliases)
  File "add_glyphs.py", line 338, in update_font_data
    add_ligature_sequences(font, seqs, aliases)
  File "add_glyphs.py", line 330, in add_ligature_sequences
    add_ligature(lookup, cmap, seq, name)
  File "add_glyphs.py", line 313, in add_ligature
    ligatures = lookup.SubTable[0].ligatures
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttLib/tables/otBase.py", line 557, in __getattr__
    raise AttributeError(attr)
AttributeError: ligatures
Makefile:197: recipe for target 'NotoColorEmoji.tmpl.ttx' failed
make: *** [NotoColorEmoji.tmpl.ttx] Error 1
rm build/emoji/emoji_u1f57a_1f3ff.png

```

**Comment by dougfelt** [comment]
@bitfag, this looks like the original problem that I provided a patch for upthread.  I just pushed the patch.  The way things are going I suppose you'll now encounter the problem benjamfield most recently encountered, which I also (still) can't reproduce. Let me know how it goes.

@behdad, any idea what might be causing this difference in behavior between what I see and what benjamfield sees?  For both of us ttx reports version 3.7.3.dev0, so I assume we are using the same fontTools. Does ttx read/write of xml have other dependencies we need to check?

**Comment by bitfag** [comment]
Now I'm getting the same error as benjamfield (AttributeError: classDefs).

**Comment by behdad** [comment]
No idea.

**Comment by julroy67** [comment]
Got the same error with archlinux [nototools package](https://www.archlinux.org/packages/extra/any/nototools/) (git20160719), but updating nototools to [HEAD](1498e738409a8fde3a157d00ad320ffb3500d498) fixes the issue.

**Comment by benjamfield** [comment]
Sorry for the delay. Here's the output:

```
optipng -quiet -o7 -clobber -force -out "build/compressed_pngs/emoji_u1f3f4_e0067_e0062_e0077_e006c_e0073_e007f.png" "build/quantized_pngs/emoji_u1f3f4_e0067_e0062_e0077_e006c_e0073_e007f.png"
cannot process alias fe82b -> unknown_flag
INFO:fontTools.misc.xmlReader:Parsing 'GlyphOrder' table...
INFO:fontTools.misc.xmlReader:Parsing 'head' table...
INFO:fontTools.misc.xmlReader:Parsing 'hhea' table...
INFO:fontTools.misc.xmlReader:Parsing 'maxp' table...
INFO:fontTools.misc.xmlReader:Parsing 'OS/2' table...
INFO:fontTools.misc.xmlReader:Parsing 'hmtx' table...
INFO:fontTools.misc.xmlReader:Parsing 'vhea' table...
INFO:fontTools.misc.xmlReader:Parsing 'vmtx' table...
INFO:fontTools.misc.xmlReader:Parsing 'cmap' table...
INFO:fontTools.misc.xmlReader:Parsing 'name' table...
INFO:fontTools.misc.xmlReader:Parsing 'post' table...
INFO:fontTools.misc.xmlReader:Parsing 'GSUB' table...
INFO:fontTools.ttLib:Dumping 'GlyphOrder' table...
INFO:fontTools.ttLib:Dumping 'head' table...
INFO:fontTools.ttLib:Dumping 'hhea' table...
INFO:fontTools.ttLib:Dumping 'maxp' table...
INFO:fontTools.ttLib:Dumping 'OS/2' table...
INFO:fontTools.ttLib:Dumping 'hmtx' table...
INFO:fontTools.ttLib:Dumping 'cmap' table...
INFO:fontTools.ttLib:Dumping 'name' table...
INFO:fontTools.ttLib:Dumping 'post' table...
INFO:fontTools.ttLib:Dumping 'GSUB' table...
Traceback (most recent call last):
  File "add_glyphs.py", line 409, in <module>
    main()
  File "add_glyphs.py", line 405, in main
    args.aliases)
  File "add_glyphs.py", line 380, in update_ttx
    font.saveXML(out_file)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 308, in saveXML
    self._tableToXML(tableWriter, tag, progress)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 346, in _tableToXML
    table.toXML(writer, self)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 113, in toXML
    self.table.toXML2(writer, font)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 721, in toXML2
    conv.xmlWrite(xmlWriter, font, value, conv.name, [])
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 332, in xmlWrite
    value.toXML(xmlWriter, font, attrs, name=name)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 702, in toXML
    self.toXML2(xmlWriter, font)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 716, in toXML2
    [("index", i)])
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 332, in xmlWrite
    value.toXML(xmlWriter, font, attrs, name=name)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 702, in toXML
    self.toXML2(xmlWriter, font)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 716, in toXML2
    [("index", i)])
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 413, in xmlWrite
    Table.xmlWrite(self, xmlWriter, font, value, None, attrs)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 332, in xmlWrite
    value.toXML(xmlWriter, font, attrs, name=name)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 775, in toXML
    BaseTable.toXML(self, xmlWriter, font, attrs, name)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 702, in toXML
    self.toXML2(xmlWriter, font)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 721, in toXML2
    conv.xmlWrite(xmlWriter, font, value, conv.name, [])
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 332, in xmlWrite
    value.toXML(xmlWriter, font, attrs, name=name)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 775, in toXML
    BaseTable.toXML(self, xmlWriter, font, attrs, name)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 702, in toXML
    self.toXML2(xmlWriter, font)
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otTables.py", line 471, in toXML2
    items = sorted(self.classDefs.items())
  File "/home/benjamfield/.envs/emoji/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 557, in __getattr__
    raise AttributeError(attr)
AttributeError: classDefs
Makefile:197: recipe for target 'NotoColorEmoji.tmpl.ttx' failed
make: *** [NotoColorEmoji.tmpl.ttx] Error 1
rm build/emoji/emoji_u1f645_1f3fc_200d_2642.png NotoColorEmoji.tmpl.ttx
```

**Comment by dougfelt** [comment]
Haven't heard more about this.  Works for me so I can't reproduce.  The docker environment should help to ensure people have the same tools (though it still needs tweaking for the emoji build, some updates are coming).
